canton {
  remote-participants {
    p-treasury {
      admin-api { address = "127.0.0.1", port = 5012 }
      ledger-api { address = "127.0.0.1", port = 5011 }
    }
    p-cash {
      admin-api { address = "127.0.0.1", port = 5022 }
      ledger-api { address = "127.0.0.1", port = 5021 }
    }
    p-seller {
      admin-api { address = "127.0.0.1", port = 5032 }
      ledger-api { address = "127.0.0.1", port = 5031 }
    }
    p-buyer {
      admin-api { address = "127.0.0.1", port = 5042 }
      ledger-api { address = "127.0.0.1", port = 5041 }
    }
    p-venue {
      admin-api { address = "127.0.0.1", port = 5052 }
      ledger-api { address = "127.0.0.1", port = 5051 }
    }
    p-outsider {
      admin-api { address = "127.0.0.1", port = 5062 }
      ledger-api { address = "127.0.0.1", port = 5061 }
    }
  }
}
