canton {
  sequencers {
    settlement-sequencer {
      storage.type = memory
      public-api.port = 5001
      admin-api.port = 5002
    }
  }

  mediators {
    settlement-mediator {
      storage.type = memory
      admin-api.port = 5003
    }
  }

  participants {
    p-treasury {
      storage.type = memory
      ledger-api.port = 5011
      admin-api.port = 5012
      http-ledger-api.enabled = false
    }
    p-cash {
      storage.type = memory
      ledger-api.port = 5021
      admin-api.port = 5022
      http-ledger-api.enabled = false
    }
    p-seller {
      storage.type = memory
      ledger-api.port = 5031
      admin-api.port = 5032
      http-ledger-api.enabled = false
    }
    p-buyer {
      storage.type = memory
      ledger-api.port = 5041
      admin-api.port = 5042
      http-ledger-api.enabled = false
    }
    p-venue {
      storage.type = memory
      ledger-api.port = 5051
      admin-api.port = 5052
      http-ledger-api.enabled = false
    }
    p-outsider {
      storage.type = memory
      ledger-api.port = 5061
      admin-api.port = 5062
      http-ledger-api.enabled = false
    }
  }
}
