[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
confidential_escrow = "9Yuvt4HxfbGCL9gPk3ygMLV3UdrMFgAJsyhdoJvbKcUD"

[programs.devnet]
confidential_escrow = "BkDwMbtMVhDWeQ1nHwvCKmTT2XZhP2RMYGw18c6imnPf"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/confidential-escrow"]
